---
- name: Install and configure Apache web server
  package:
    name: httpd
    state: latest

- name: Create files on the automation server
  copy:
    content: "{{ inventory_hostname }}"
    dest: "/tmp/{{ inventory_hostname }}.html"
  delegate_to: localhost

- name: Copy the files to respective managed nodes
  copy:
    src: "/tmp/{{ inventory_hostname }}.html"
    dest: /var/www/html/index.html
    mode: 0444
    remote_src: yes

- name: Start the Apache web server
  service:
    name: httpd
    state: started
    enabled: yes
  notify: restart apache
